# Generated by Django 4.0.4 on 2022-05-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avancada', '0002_bitola_conexoe_delete_bitolas_delete_conexoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadavancada',
            name='concessionaria',
        ),
        migrations.RemoveField(
            model_name='leadavancada',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='leadavancada',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leadavancada',
            name='telefone',
        ),
    ]
