# Generated by Django 4.0.4 on 2022-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avancada', '0003_remove_leadavancada_concessionaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadavancada',
            name='tipo_cabo',
            field=models.CharField(default=220, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadavancada',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
