# Generated by Django 4.0.4 on 2022-05-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0002_rename_lead_leadbasica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadbasica',
            name='mchs',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='potencia',
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='concessionaria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='modelo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
