# Generated by Django 4.0.4 on 2022-05-05 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0003_remove_leadbasica_mchs_remove_leadbasica_potencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadbasica',
            name='concessionaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='cpf_cnpj',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='modelo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadbasica',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
