# Generated by Django 4.0.4 on 2022-05-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0004_alter_leadbasica_concessionaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadbasica',
            name='concessionaria',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='data',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='leadbasica',
            name='telefone',
        ),
    ]
