# Generated by Django 4.0.4 on 2022-05-12 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0005_remove_leadbasica_concessionaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbasica',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
