# Generated by Django 4.0.4 on 2022-05-12 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0006_leadbasica_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbasica',
            name='potencia',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
