# Generated by Django 4.0.4 on 2022-05-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0007_leadbasica_potencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadbasica',
            name='potencia',
        ),
    ]
