# Generated by Django 4.0.4 on 2022-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0008_remove_leadbasica_potencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbasica',
            name='potencia',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
