# Generated by Django 4.0.4 on 2022-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basica', '0009_leadbasica_potencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbasica',
            name='mchs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
